# Generated by Django 5.2.8 on 2025-12-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_faq_student_alter_employee_table_faqgroup'),
    ]

    operations = [
    ]
