# Generated by Django 4.2.30 on 2026-05-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_faqgroup_faq_delete_student_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='regi_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
