# Generated by Django 4.2.30 on 2026-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_employee_regi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
