# Generated by Django 4.2.30 on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_employee_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
    ]