# Generated by Django 4.2.30 on 2026-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_employee_address_age_dob_department_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
